### ISSUE TITLE
Operation Order in Sidebar

### ISSUE THREAD

**Issue by JacobEberhardt** [blockchain-it-hr/zokrates-remix-plugin#22]
Currently, the order of operations is Compile, Setup, Export-Verifier, Compute, Generate-Proof.

Yet, when developing, compilation and witness computation are often performed independently from the other steps. It may thus make sense to move "Compute" to the second position, also to indicate that it can be run without first performing a setup.

**Comment by dark64** [comment]
Great suggestion. Fixed in https://github.com/blockchain-it-hr/zokrates-remix-plugin/pull/23
